import React, { useEffect, useState } from 'react';
import { Archive, Clock3, MessageSquare, MoreHorizontal, Trash2 } from 'lucide-react';
import { Conversation, archiveConversation, deleteConversation, getUserConversations } from '../services/conversationService.ts';

interface Props { userId: string; currentConversationId?: string; onSelectConversation: (id: string) => void; onNewConversation: () => void; }
export const ConversationHistory: React.FC<Props> = ({ userId, currentConversationId, onSelectConversation, onNewConversation }) => {
  const [items, setItems] = useState<Conversation[]>([]);
  const [archived, setArchived] = useState(false);
  const [loading, setLoading] = useState(true);
  const [menu, setMenu] = useState<string | null>(null);
  const load = async () => { setLoading(true); try { const result = await getUserConversations(userId, 50, 0, archived); setItems(result.conversations); } catch (error) { console.error(error); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [userId, archived]);
  const relative = (value: string) => { const diff = Date.now() - new Date(value).getTime(); const minutes = Math.floor(diff / 60000); if (minutes < 1) return 'Just now'; if (minutes < 60) return `${minutes}m`; const hours = Math.floor(minutes / 60); if (hours < 24) return `${hours}h`; return `${Math.floor(hours / 24)}d`; };
  return <div className="conversation-panel"><div className="conversation-heading"><span>{archived ? 'Archived' : 'Recent'}</span><button onClick={() => setArchived((value) => !value)}>{archived ? 'Active' : 'View archived'}</button></div>{loading ? <div className="empty-history">Loading your threads…</div> : items.length === 0 ? <div className="empty-history">No conversations yet.<br />Start a new one above.</div> : items.map((item) => <div className={`conversation-item ${currentConversationId === item.conversation_id ? 'active' : ''}`} key={item.conversation_id} role="button" tabIndex={0} onClick={() => onSelectConversation(item.conversation_id)} onKeyDown={(event) => event.key === 'Enter' && onSelectConversation(item.conversation_id)}><MessageSquare size={14} /><span className="conversation-item-title">{item.title || 'New conversation'}<span className="conversation-item-meta"><Clock3 size={10} style={{ verticalAlign: 'middle', marginRight: 3 }} />{relative(item.updated_at)} · {item.messages.length} messages</span></span><button className="conversation-more" title="Actions" onClick={(event) => { event.stopPropagation(); setMenu(menu === item.conversation_id ? null : item.conversation_id); }}><MoreHorizontal size={14} /></button>{menu === item.conversation_id && <div className="menu-card" style={{ top: 34, right: 8, minWidth: 130 }}>{!item.is_archived && <button onClick={async (event) => { event.stopPropagation(); await archiveConversation(item.conversation_id); setMenu(null); load(); }}><Archive size={13} /> Archive</button>}<button onClick={async (event) => { event.stopPropagation(); await deleteConversation(item.conversation_id); setMenu(null); load(); if (currentConversationId === item.conversation_id) onNewConversation(); }}><Trash2 size={13} color="#d92d20" /> Delete</button></div>}</div>)}</div>;
};
